Add proxy support
SUSE-Enceladus/instance-billing-flavor-check pull request #11
Opened 2024-01-16 10:33 UTC by jesusbv

2024-01-16 10:34 UTC, jesusbv commented
version `0.0.5` is on #10

2024-01-17 13:23 UTC, rjschwei requested changes

2024-01-17 13:23 UTC, rjschwei commented on lib/instance_billing_flavor_check/utils.py
> +        logger.info('Using proxy settings present on the environment.')
s/on/in/

2024-01-17 13:23 UTC, rjschwei commented on lib/instance_billing_flavor_check/utils.py
> +        logging.info('No proxy config file found on %s', PROXY_CONFIG_PATH)
The user is not telling us to use a proxy, it is a discovery process, as such there is no need to tell the user anything about our discovery process. `pass` or `return`

2024-01-17 13:23 UTC, rjschwei commented on lib/instance_billing_flavor_check/utils.py
> +    return proxies or None
The empty dict will evaluate to `False` anywhere we have to check if there is a proxy as such the return of `None` is superfluous.

2024-01-17 13:23 UTC, rjschwei commented on lib/instance_billing_flavor_check/utils.py
> +            proxies=proxies
Will work with an empty `{}`

2024-01-19 15:29 UTC, rjschwei approved these changes

2024-01-19 15:29 UTC, merged